### PR TITLE
add inputSourceMap option & prepack standalone sourceMaps option

### PR DESCRIPTION
**Pull request by huanz**

### CODE REVIEW

**Comment by hermanventer** [comment]
How does this relate to #536?

**Comment by sebmarkbage** [comment]
#536 only concerns the output in the CLI. This is the __input__ in the API.

@huanz Could you add the same option to the `prepack-node` APIs so that if you specify it there it doesn't get ignored? You can conditionally use `inputSourceMapFilename` or `inputSourceMap` in that case.

**Comment by huanz** [comment]
@sebmarkbage the `prepack-node` methods `prepackFile` and `prepackFileSync` already has sourceMap option，other methods exports from `prepack-standalone` i have already changed

**Comment by NTillmann** [comment]
Closing due to inactivity and missing CLA.

**Pull request closed without merging**
