### PR TITLE
Ensures all serializer test case output passes linting validation

### PR DESCRIPTION
**Pull request by trueadm**
Release notes: all serializer tests now get linted via ESlint for correct output

This PR is pretty gigantic, but almost 99% of it is changing all the serializer tests so they pass the linting rules – which means that there must be no undefined variables or if they are, they are explicitly accesses via `global`. Furthermore, the linting also checks to ensure that all variables are defined before they are used.

Also I added a regression test `conditions3` that further validates some complex cases I was seeing fail in other cases. The ESlint config is also in its own module so it can be shared between `debug-fb-www`.

### CODE REVIEW

**Comment by NTillmann** [comment]
This is awesome!

But also a little bit concerning: It looks like you cut out of the test matrix any kind of code that doesn't pass the linter.

**Comment by NTillmann** [comment]
There should be a way in the test runner to disable the linter, and then we should have a bunch of tests that exercise exactly that linter-violating behavior.

**Comment by NTillmann** [comment]
I don't mind going ahead with the changes now, but then also open an issue to still do what I suggested...

**Comment by trueadm** [comment]
@NTillmann How do you mean? All the tests still run, I've not removed any tests. I've had to add variable declarations or explicit global – but that's a good thing in the long run, as it means our tests follow best practices for actual JS too. Feel free to add a flag to disable the linter on some tests. :)

**Comment by NTillmann** [comment]
Just to clarify my concern about what we are cutting out of the test matrix here: I am concerned about cutting out testing that Prepack can handle non-linting *input*. The output, at least the non-residual code Prepack generates, should indeed pass the linter in most cases.

Besides adding back some tests, the only other way to keep things nicely tested would be to run the Linter on the input before running the actual Prepack logic, rejecting non-linting programs there too. But that would make Prepack slower, and also be limiting to any user who doesn't agree with our exact lint rules.

**Pull request closed without merging**
