### PR TITLE
Better handling of this with simple React class components

### PR DESCRIPTION
**Pull request by trueadm**
Release notes: none

This fixes bugs around detecting independent dangling `this` keywords in methods of a React class component and correctly bailing out upon finding them. This is typically used in cases where we'd want to bail out, for example:

```js
let self = this;
let handleClick = function () { console.log(self.x) };
return <div onClick={handleClick} />
```

or:

```js
let handleClick = function () { console.log(this.x) };
return <div onClick={handleClick.bind(this)} />
```

### CODE REVIEW

**Comment by gaearon** [comment]
Worried this will be slow. Is it not on a large bundle?

**Comment by trueadm** [comment]
@gaearon I'd rather we were correct and addressed performance when it becomes the primary issue. For now this is not for first render route too, so it shouldn't affect current work.

**Comment by gaearon** [comment]
Will/can this also find arrows?

**Comment by trueadm** [comment]
@gaearon Not at this point, as arrow functions are not supported. I'll make a not on my arrow function PR to include logic for this too. https://github.com/facebook/prepack/pull/1650

**Pull request closed without merging**
