### PR TITLE
Rest syntax

### PR DESCRIPTION
**Pull request by prometheansacrifice**
Release note: Adds support for rest syntax. Abstract Interpreter support pending.
Addresses #927

### CODE REVIEW

**Comment by prometheansacrifice** [comment]
Flow keeps crashing with `Flow_error.EMergeTimeout(105.016726017)`. There already is an [open issue](https://github.com/facebook/flow/issues/6155)

**Comment by prometheansacrifice** [comment]
@hermanventer Can I please get some help with test262 tests? I'm not able to figure out which tests are failing because of this PR. I did spot some destructuring related failures earlier. Fixed them.

**Comment by hermanventer** [comment]
Please rebase this when PR #2092 has been merged.

**Comment by trueadm** [comment]
@prometheansacrifice Please can you merge in master on this PR?

**Comment by prometheansacrifice** [comment]
@trueadm All tests pass :)

**Pull request closed without merging**
