### PR TITLE
Failing to run prettier should block CI

### PR DESCRIPTION
**Pull request by wdhorton**
I tested that `yarn prettier-ci-check` logs an error and exits with code 1 if your code isn't formatted, but obviously I couldn't test the `circle.yml` changes.

### CODE REVIEW

**Comment by wdhorton** [comment]
Well, this is failing on the `prettier-ci-check`, so I guess we know that works too.

**Comment by NTillmann** [comment]
So, I ran prettier over the code base (#778), but somehow the new `prettier-ci-check` check still fails with no useful message. Any idea what's going on, @wdhorton?

**Comment by NTillmann** [comment]
Okay, figured it out... Apparently, there are still a few offendingly formatted files, and unfortunately, the prettier-ci-check output just doesn't say what they are. Will fix those files, and then try this again.

**Comment by NTillmann** [comment]
Incorporated by referenced pull request.

**Pull request closed without merging**
