### PR TITLE
Add open source logo to footer

### LINKED ISSUE #569: Website footer missing logo
Should probably include Facebook Open Source logo as per others

### PR DESCRIPTION
**Pull request by JoelMarcey**
Fixes #569

### CODE REVIEW

**Comment by TheSavior** [comment]
Adding a screenshot of this diff:

screen shot 2017-05-05 at 1 40 36 pm

**Comment by TheSavior** [comment]
Updated the colors and width so it now looks like this:

screen shot 2017-05-05 at 1 57 56 pm

**Comment by TheSavior** [comment]
Thanks for contributing @JoelMarcey !

**Comment by jamesgpearce** [comment]
👓

**Pull request merged**
