### PR TITLE
Add tests for nested conditional regressions

### PR DESCRIPTION
**Pull request by calebmer**
@gaearon found a regression to the cases I fixed in #2255. The following code:

```js
function fn1(arg) {
  if (arg.foo()) {
    if (arg.bar()) {
      return 42;
    }
  }
}

function fn2(arg) {
  if (arg.foo()) {
    if (arg.bar()) {
      return 1;
    }
  } else {
    return 2;
  }
}

if (global.__optimize) {
  __optimize(fn1);
  __optimize(fn2);
}
```

Now compiles to:

```js
var fn1, fn2;
(function() {
  var _$4 = this;

  var _0 = function(arg) {
    var _$0 = arg.foo();

    if (_$0) {
      var _$1 = arg.bar();
    }

    if (_$0) {
      var _$1 = arg.bar(); // <----------------------------- `arg.bar()` is redeclared.
    }

    return _$0 ? (_$1 ? 42 : void 0) : void 0;
  };

  var _8 = function(arg) {
    var _$2 = arg.foo();

    var _$3 = arg.bar(); // <------------------------------- `arg.bar()` should be inside `if (_$2)`

    return _$2 ? (_$3 ? 1 : void 0) : 2;
  };

  _$4.fn1 = _0;
  _$4.fn2 = _8;
}.call(this));
```

After looking through the commits, I found that #2274 regressed this case. After reverting that PR I found that these cases were fixed again, but interestingly the test added in that PR also passed after I reverted the change.

I’m opening this PR with the failing tests so @hermanventer can take a look. I haven’t looked too deeply into this case, so I’m probably missing something important. Maybe some race condition between the landing of #2255 and #2274?

### CODE REVIEW

**Comment by trueadm** [comment]
I looked into this too and feel the right strategy is to probably revert https://github.com/facebook/prepack/pull/2274. What do you think @hermanventer?

**Comment by calebmer** [comment]
Reverting #2274 to demonstrate tests still pass. (Include the case added in that PR.)

**Comment by hermanventer** [comment]
I suspect that landing this would create merge conflicts for #2402. Once that is landed, I expect the tests to pass and you can land them without having to revert #2274.

**Comment by calebmer** [comment]
Finally rebased past @hermanventer’s changes. These tests are fixed! We can land them as regression tests.

**Pull request closed without merging**
