### PR TITLE
Rethrow all errors during React reconciliation other than bail-outs

### PR DESCRIPTION
**Pull request by trueadm**
Release notes: none

Moving forward, we no longer want to bail out when we have a Prepack `FatalError` or any other error other than an expected bail-out. This is also shows up the test that currently fails but passed before.

Adds CompilerDiagnostic/RecoverableError -`PP0023: failed to reconcile a React component tree due to a Prepack evaluation error`

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Why is this?

**Comment by trueadm** [comment]
@sebmarkbage We need all the render phase to be evaluated and not bail-out with errors so that we can serialize to bytecode properly.

**Comment by sebmarkbage** [comment]
So we’d rather fail the build than accept a fallback? Seems like it would be better to log diagnostic information and continue compiling like other recoverable errors.

We can downstream fail the build if we choose to but seems good to have the option to bail.

By continuing we also collect other possible deopts into the logs so that when compiling you can get a good idea of how many things you have to address to get to a fully evaluated state - rather than getting one by one and then giving up.

**Comment by trueadm** [comment]
@sebmarkbage The idea was to throw a `CompilerDiagnostic` error. Is that what you meant?

**Comment by sebmarkbage** [comment]
Something like this where it conditionally throws and otherwise bails out with a comment.

https://github.com/facebook/prepack/blob/f4c46000e20f46b054b1d04ce5e42c89a02ae46d/src/evaluators/WithStatement.js#L36-L37

**Comment by trueadm** [comment]
Actually, I think we should abandon this PR for now. After thinking about this, there's not any real value in changing how the errors are thrown at this time. We can revisit this later.

**Pull request closed without merging**
