### PR TITLE
babel-core updated to 6.26.3

### LINKED ISSUE #2181: yarn install fails because of dependency upath@1.0.4 Node 10.x
Getting following error while installing dependencies. Upath is a dependency of babe-core. So an update of babel-core solves the problem.
`error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".`

### PR DESCRIPTION
**Pull request by LaRuaNa**
fixes #2181

### CODE REVIEW

**Comment by hermanventer** [comment]
The new version of BabelCore does not seem to work with test-react.

**Comment by LaRuaNa** [comment]
Yea seems like some mocks are failing. I'm checking it but might need some help. I'm not that much familiar with prepack codebase yet :)

**Comment by hermanventer** [comment]
Your yarn.lock file has a lot of changes to it. When I do the same thing on my machine I see only a few changes. Perhaps revert those changes and try again?

**Comment by LaRuaNa** [comment]
Since yarn fails checking dependencies i can't use `yarn upgrade` so i removed yarn.lock and that causes a lot of changes because yarn updates several packages. Moreover seems like there are another packages depending on upath. And the reason why react tests fail seems to be an incompatibility with react-relay which is also updated from 1.4.1 to 1.6.0

**Comment by gaearon** [comment]
You shouldn't need to run `yarn upgrade`.

Instead, revert your changes and then run `yarn add -D babel-core@6.26.3`.

**Comment by LaRuaNa** [comment]
Well, since yarn fails while checking packages i can't run `yarn add -D`. But I'll give it a try in a container with compatible node version

**Comment by trueadm** [comment]
@LaRuaNa I updated Prepack to use Babel 7, so hopefully this issue is fixed. @LaRuaNa can you please check and let me know? Closing this PR now as we're on Babel 7.

**Comment by LaRuaNa** [comment]
@trueadm Thanks for fix works well :)

**Pull request closed without merging**
