### PR TITLE
Ensure we visit ReactLibrary with React.Fragment usage

### PR DESCRIPTION
**Pull request by trueadm**
Release notes: none

This PR ensures we visit the React library when `React.Fragment` is used in a ReactElement. Fixes https://github.com/facebook/prepack/issues/1831.

### CODE REVIEW

**Comment by gaearon** [comment]
Why does this help? What's special about fragments per se (as opposed to e.g. context consumers/providers)?

**Comment by trueadm** [comment]
@gaearon The fragments are symbols that we don't visit as we don't serialize out the actual creation of the symbol (rather, it's an implementation detail in React itself0.

**Comment by gaearon** [comment]
Right, what I'm saying is that context provider type is an object that has a symbol property (which also doesn't need to be serialized). So is this only a problem when the `type` itself is a symbol?

**Comment by trueadm** [comment]
@gaearon Yep, as we don't visit the "type" of ReactElements.

**Pull request closed without merging**
