### PR TITLE
Don't insist on giving all abstract values unique names.

### LINKED ISSUE #1765: unnecessary intermediate variables in the presence of abstract values
For the following code
```js
(function () {
  let x = __abstract("number", "x");
  let y = x + 1;
  global.x = y;
})();
```
when Prepacking, even with `--inlineExpressions`, we get
```js
(function () {
  var _2 = x;
  var _0 = 1 + _2;
  x = _0;
})();
```

I don't understand why we need `_2` and `_0` as explicit variables here. They are only being referenced once, and the abstract values they represent are not temporal in any way. So one might say the output should be
```js
x = 1 + x;
```

### PR DESCRIPTION
**Pull request by NTillmann**
Release notes: More compact code generation by avoiding introducing local variables for abstract values when possible.

This fixes #1765.

### CODE REVIEW

**Comment by trueadm** [comment]
@NTillmann they needs ids for JSX. Specifically, how you reference things with JSX has particular quirks, as things lowecase `<div>` are not referenced components, but those with uppercase and `_` are referenced components, thus why `<_$1>` works. @sebmarkbage might be able to shine more light on this as he helped me get my head around these issues early on, he might have another fix.

**Comment by NTillmann** [comment]
Any way to be more selective in _what_ kind of abstract values need ids? All of them? Something that is somehow identifiable as React thingy?

**Comment by sebmarkbage** [comment]
Abstract values that are emitted as first argument to JSX elements needs an id (that doesn’t start with lower case a-z). Could be marked by the visitor?

**Comment by sebmarkbage** [comment]
Specifically this `type` value is the thing that needs an ID. https://github.com/facebook/prepack/blob/master/src/serializer/ResidualReactElementVisitor.js#L45
https://github.com/facebook/prepack/blob/master/src/serializer/ResidualReactElementSerializer.js#L252

**Comment by NTillmann** [comment]
Thanks for the pointers, @sebmarkbage! It's easy to force an id just for that case.

**Comment by NTillmann** [comment]
> an id (that doesn’t start with lower case a-z)
What's the background of this restriction?

**Comment by sebmarkbage** [comment]
React's form of JSX needs to know if something is a HTML tag or local identifier. Using a special syntax like `{}` was too much since both are very common and the whole point is to make it more readable.

The typical convention for a component, just like classes, is to use a capital.

```js
var Foo = require('bar/foo');
<Foo />;
```

The convention for HTML however is lower case these days.

```js
<div />;
```

We used to have a whitelist of HTML tags but new ones get added so it became a pain to maintain across the ecosystem.

We considered having local scoping but at the time it was difficult for transpilers to know their true scope given that they could be running pre-bundled or post-bundled. There's also a quirk that `i` is both popular in loops and in JSX.

```js
var items = [];
for (var i = 0; i < 10; i++) {
  items.push(<li>Foo <i>Bar</i></li>);
}
```

So we settled on a convention based on case. It worked out surprisingly well and now it's standard practice and has leaked to other systems like Glimmer.

**Pull request closed without merging**
