### PR TITLE
Make master/docs a single source of truth for gh-pages

### PR DESCRIPTION
**Pull request by j-nolan**
Release note: none

To address issue #956 .

The idea is to have all documentation (aka "the website") in a single `docs/` directory on the `master` branch like [Jest](https://github.com/facebook/jest/tree/master/docs) and [Relay](https://github.com/facebook/relay/tree/master/docs) do. This directory then serves as a single source of truth to publish the `gh-pages` branch.

This PR:
- Moves the current content of the `gh-pages` branch to a `docs/` directory in `master`
- Provides a bash script for maintainers to easily publish the `gh-pages` branch from the `docs/` directory. The script also builds `prepack.min.js` from master to make sure gh-pages always has the latest version of prepack.

Additionally, I noticed the `gh-pages` branch had two `prepack.min.js` files (one in `./` and one in `./js/`). I removed the first one because it is apparently not used but it may break other websites if they references that file.

# Test plan
0. Fork the repo to avoid modifying the real website

1. Change the site
`> git checkout master`
`> echo ".nav { background-color: chartreuse; }" >> docs/css/style.css`
`> git add docs/css/style.css`
`> commit -m "The navigation bar looks better in green"`
`> git push`

2. Run the publication script: 
`> ./scripts/publish-gh-pages.sh`

3. Verify that the gh-pages has been updated:
`> git checkout gh-pages`
`> git pull`
`> git diff HEAD~ # should show the line you added`

### CODE REVIEW

**Comment by NTillmann** [comment]
Looks great! 

This went a little bit further that was I originally thought, by including the compiled assets, most notably js/prepack.min.js, in the Prepack master branch itself. That's a bit redundant. Similar for a bunch of the other files like prism.js or tether.min.js which could be fetched from elsewhere while building gh-pages.

I've to think a bit about what's best... I am a bit afraid that the churn on prepack.min.js will bloat our repo size. @sebmarkbage, do you have any opinions on this?

**Comment by j-nolan** [comment]
Thanks for reviewing!

To avoid storing dependencies on the repo we could refactor the site as an app with a proper `package.json` and dev/build scripts. That's how [Relay](https://github.com/facebook/relay/tree/master/website) and [Jest](https://github.com/facebook/jest/tree/master/website) in their `website/` directories. And they   store markdown doc files in a separate `docs/` directory.

**Comment by artiebits** [comment]
@j-nolan nice job! 

Relay and Jest use Docusaurus to generate their websites from `website` and `docs` directories, but unfortunately it isn’t officially public yet. And there is a lot of work to do if you want to refactor the current site in that way. And also Relay and Jest don’t have playgrounds like Prepack has.

I am not so experienced in bash scripting but is it possible to not store prepack.min.js and just generate it for gh-pages? 

Also maybe it's better to remove tether.min.js and etc. from repo and just import them into html files as external resources (@NTillmann why you don't use tether.min.js and select.min.js from some cdn)?

**Comment by j-nolan** [comment]
Hello,

> I am not so experienced in bash scripting but is it possible to not store prepack.min.js and just generate it for gh-pages?

Yes, that would be possible and would avoid redundancy. We would just have to add a build step in the "How to edit the website" section of the README but I think it's a reasonable tradeoff.

Good point about loading from CDNs. Tether as a version available on cloudflare. Can't find one for select.js though.

**Comment by artiebits** [comment]
@j-nolan It's here https://cdnjs.com/libraries/tether-select. 
So, we can remove `tether`, `select` and `select-theme-dark` from the repo.

**Comment by j-nolan** [comment]
Following suggestions by @artiebits I amended my PR as follows: 
- Don't store `prepack.min.js` on repo, ask collaborators to build it from sources
- Load `tether` and `tether-select` from CDN instead of storing the bundles in the repo

I also renamed `docs/` to `website/` to make it clear that it contains the website rather than the raw documentation.

Additional notes:
- I noticed the CDN served a slightly different version of `select-dark-theme.css`. In fact, the only difference is that [a single rule was added](https://github.com/facebook/prepack/blob/55bd4217476cbbd3ce865533de2c414a58419d48/css/select-theme-dark.css#L26). I don't know what that rule used to fix but I suspect it's not needed anymore. Perhaps @sheweichun could confirm?
- I checked if we could also load prism.js from CDN. Since it's a custom build, and I didn't find a CDN that provided that same custom build ([clike + javascript](http://prismjs.com/download.html?themes=prism&languages=clike+javascript)), I left it in the repo. But I believe 11KB is still reasonable

@NTillmann what do you think of that new version?

**Pull request closed without merging**
