### PR TITLE
[WIP] Add explicit object leaking and expand on leaking of bindings

### PR DESCRIPTION
**Pull request by trueadm**
Release notes: adds object leaking functionality and allows for objects to leak without havocing

This PR is my take on how we might implement leaking, including a test (more to come). This PR adds the following changes:

- Objects can now be leaked via the singleton `Leak.value(realm, value)`. Leaking works like havocing, except it doesn't havoc the object. The object properties can still be read, but object properties that are deleted/set will result in temporal entries.
- Bindings now have a `leakStatus` of either `READ_ONLY` and `NO_READ_WRITE`. This allows bindings to be read, but not written to.
- Havocing always leaks objects.
- Changed a bunch of call-sites to reflect theses changes
- Array.prototpe nested optimized functions use the new leaking behaviour which fixes existing bugs
- `cleanInstance` in referentializer used to clean the `leakedIds` array, but this actually brought along bugs for ids that were already serialized in the array and got lost when we cleared the array.

Please let me know if there's something that doesn't make sense or looks somewhat wrong.

Fixes https://github.com/facebook/prepack/issues/2405.

### CODE REVIEW

**Comment by NTillmann** [comment]
This looks great! Sapan (@sb98052), can you review thoroughly to make sure this is aligned with the long-term plan?

**Comment by sebmarkbage** [comment]
How are you expecting to use this?

There's a subtle thing that only works *because* we havoc. There is a rule:

__Any abstract topVal is never allowed to be any object that hasn't havoced.__

This means that you can never return an abstract topVal from any of the leaked functions if that might return a known object.

```js
var obj = {foo: 1};
var obj2 = [1].map(() => obj)[0];
obj2.foo = 2; // If obj2 is an abstract topVal we only emit an assignment, we don't actually update obj
return obj.foo; // Now if this hasn't havoced, we assume that the value is still 1
```

So this doesn't actually solve that use case.

**Comment by trueadm** [comment]
@sebmarkbage Please can you add the test cases to this PR when you have time?

**Comment by sb98052** [comment]
It's fantastic that you were able to get this working.

That said a few aspects of this conflict with my long term roadmap that it would be good to get resolved.

- The terminology you have used is inconsistent with the one that we have been moving towards. We want to use leaking and havocing as principled terms based on the conditions in which they occur, rather than definitions that are tied to the implementation. It's not clear to me what the purpose of cloning leaking and havocing is (is it to transitively materialize, if so, we should extend MaterializeImplementation). And why do we need to track them with two flags. For havocing, we have `topVal`. For havocing of bindings we don't have this - but that needs to be fixed (#2446).

- It is not clear to me that "leaked for read" and "leaked for write" should be attributes of a binding. Environment bindings that are transitively captured by a function and written to should get materialized before the call and leaked and havoced after. Ones that are only read should transitively materialize. But I think the binding itself should be represented with leaked and havoced values (#2446).

Another thought is that keeping this state beyond calls only makes sense if the capturing function leaks into the environment, which I think we don't support for nested optimized functions. So we could, at least for now, make it a requirement that the function is not leaked and only used once. That ought to fix this test:

```js
function f(c) {
  var arr = Array.from(c);
  let a = 0;
  function op(x) {
    let y = 5;
    let z = 7;
    let v = y + z;
    return v + a;
  }
  let ret0 = arr.map(op);
  a = 2;
  let ret = ret0.map(op);
  return ret;
}
__optimize(f);
inspect = () => f();
```

I propose that we proceed in two steps: 

1) Unblock the current use case by merging in what is necessary - namely, materializing "bindings that are read" transitively.

2) This should buy us time. In the meantime, we coordinate progress on the rest.

**Pull request closed without merging**
