### PR TITLE
Slight improvement to factorifyObject

### PR DESCRIPTION
**Pull request by NTillmann**
Treat `void 0` (and similar patterns) as a simple value that factorifyObject can operate on.

This slightly reduces code size with no adverse effects.

### CODE REVIEW

**Comment by cblappert** [comment]
Does this result in an improvement to bytecode size as well as source code size?

**Comment by NTillmann** [comment]
@cblappert: Yes! At the bytecode level, for a medium size FB internal codebase, the prepacked byte code size used to be 100.14% of the original byte code size (so a slight increase), and with this change, the size of the prepacked byte code is now at 99.91% of the original byte code size, so prepacking actually reduces bundle size! I'll post this milestone internally later today...

**Comment by yinghuitan** [comment]
@NTillmann, awesome result~! It's amazing that such a small change improved so much.
Btw: how do you measure the bytecode size? Manually or ct-scan run?

**Comment by NTillmann** [comment]
@yinghuitan: In phabricator, when you click through to the logs of "prepack-test", there a row called "gen_bytecode_sizes", and the size info is at the end of the corresponding log file. Not very elegant and can certainly be made nicer, but it was something Kishore added on during the last days of his internship.

**Pull request closed without merging**
