### PR TITLE
Display heap graph in website

### PR DESCRIPTION
**Pull request by JWZ2018**
Release note: add heap graph visualization to website
Moved from #1243 
Summary:
- read in the heap graph data from prepackSources result
- display the graph using [visjs](http://visjs.org/)

Test Plan:
- see graph display in UI

### CODE REVIEW

**Comment by JWZ2018** [comment]
screen shot 2017-12-12 at 4 34 03 pm

**Comment by yinghuitan** [comment]
Just to confirm: the new UI is not displayed by default right? What is the UI action to trigger the display?

**Comment by yinghuitan** [comment]
For "TODO: add a legend to the UI describing what the different shapes and colors mean", you added it in this diff.

**Comment by JWZ2018** [comment]
The graph UI is hidden by default. It is triggered by a button click on the "SHOW HEAP" blue button on the top right. I have updated the summary to remove the TODO.

This is the view when the page is first loaded:
screen shot 2017-12-11 at 5 23 37 pm

**Pull request closed without merging**
