### PR TITLE
[WIP] Bug: event handlers as named functions get assigned to the global object

### PR DESCRIPTION
**Pull request by gaearon**
```js
<div onClick={function onClick() {}} />
```

creates a global `onClick` function.

Attached is a regression test.

### CODE REVIEW

**Comment by trueadm** [comment]
@cblappert Any idea as to why this might be happening?

**Comment by gaearon** [comment]
My guess is that since it's a named function, Prepack erroneously thinks it's supposed to be in the global scope. Maybe it doesn't understand "where" the scope is when inside React JSX attributes?

**Comment by cblappert** [comment]
Not sure why this is happening tbh, I would have to debug it. Could be factorify trying to eliminate duplicate functions, could be Additional Functions getting the scope wrong for emitting the onclick.

**Comment by gaearon** [comment]
Tagging as [WIP] since it's just a failing test. We'd still appreciate if you could look into this. :-)

**Pull request closed without merging**
