### PR TITLE
Fix REPL Error highlighting

### PR DESCRIPTION
**Pull request by abhisheksoni27**
Currently, due to a mistake in my last pull request, the error highlighting only works if the line number is a single digit number. (I was using `slice(0,1)` :laughing: ). This is a fix for that sorcery. :tada:

### CODE REVIEW

**Comment by abhisheksoni27** [comment]
Arghh! I don't know why these previous commits are showing here, even though the `difference` is fine. Should I make a new branch and then a new PR?

**Comment by huhwhat777** [comment]
Hey I can't seem to log in r regester anywhere it says my email is not valid

**Comment by abhisheksoni27** [comment]
@cblappert Great! Also, is there a better way to bring my repository up to terms with the upstream branch other than `git fetch upstream && git merge upstream/BRANCH_NAME && git push origin BRANCH_NAME` ? :thinking:

**Comment by cblappert** [comment]
Not sure, @dulinriley might have a better answer?

**Comment by dulinriley** [comment]
You should be able to set tracking up:
```
$ git checkout BRANCH_NAME
$ git push --set-upstream remote/BRANCH_NAME
$ # After executing that you should be able to do future pushes to your branch by
$ git push # now sends to remote/BRANCH_NAME, not master
```
Keeping up to date with master is just:
```
$ git pull origin master # git pull == git fetch && git merge
```
Actually `git pull origin master` should work without tracking anyway, but with upstream tracking you don't need to specify `git push origin BRANCH_NAME` every time you want to push.

**Comment by abhisheksoni27** [comment]
@dulinriley Thanks a lot! `git pull origin upstream` did the trick. :tada:

**Pull request merged**
