### PR TITLE
Wrap the env in a pure wrapper if fb-www

### PR DESCRIPTION
**Pull request by trueadm**
Release notes: none

For internal testing we want to wrap the environment in a pure wrapper.

### CODE REVIEW

**Comment by gaearon** [comment]
AFAIK this currently breaks my compiled bundle. I'll try to come up with a test case so we can fix that before landing.

**Comment by gaearon** [comment]
Here's a minimal example.

```js
(function() {
  function App() {}
  App.prototype.hi = function() {};
  global.WrappedApp = require("RelayModern").createFragmentContainer(App);
})();
```

It compiles (with a "recoverable error" about leaking) before this change but doesn't compile anymore.

**Comment by trueadm** [comment]
@gaearon I'll add that test and fix the issue it creates.

**Comment by gaearon** [comment]
I'm chatting to @sebmarkbage, he suggested replacing that invariant with a `break` and then adding `Array` to the whitelist of "kind" `switch` cases that just `return` (that's the next error caused by this diff for UFI bundle).

**Comment by gaearon** [comment]
(After fixing those two cases I hit an invariant here: https://github.com/facebook/prepack/blob/a39eff31dd5bd179b47122fbaf1f97f09f669e44/src/serializer/ResidualHeapSerializer.js#L1486)

**Comment by trueadm** [comment]
@gaearon Yep, I've done that locally and found the same too. This is caused by the length of the array being returned as an `AbstractValue` rather than `NumberValue` because the array has been marked as non-pure. Looking into a solution now.

**Comment by trueadm** [comment]
Follow up PR created: https://github.com/facebook/prepack/pull/1377

**Pull request closed without merging**
