### PR TITLE
Update package.json engines field

### PR DESCRIPTION
**Pull request by sebmarkbage**
yarn warns about this.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Interesting. The node environment that I have been building out shims for is 7! So it won't work with 6 atm. :)

**Comment by hermanventer** [comment]
Can you run "npm run validate" on your system without any issue? If so, can you tell us which version of Node you are using to run it?

**Comment by sebmarkbage** [comment]
I can confirm that I'm hitting this bug with `v7.9.0`.
screen shot 2017-05-04 at 3 24 27 pm

**Comment by sebmarkbage** [comment]
The only place I can repro it is in tests though. It seems like a bug in contextify (the "vm" module used by the test runner).
 
```js
var vm = require('vm');
let script = new vm.Script(`
  var global = this; var self = this;
  Object.defineProperty(global, "p", {
    configurable: true,
    enumerable: true,
    get: function () { throw new Error("42"); }
  });
`, { cachedDataProduced: false });
script.runInNewContext({});
```

If that's the only case I think we should expand the allowed engine range so that people can use the npm package outside of contributing to the project itself (i.e. running tests). While we try to fix the test.

**Comment by sebmarkbage** [comment]
So what happens is that `contextify` tries to copy all the properties over and one of them throws. I'll file an issue with Node.

**Comment by sebmarkbage** [comment]
I have been getting some additional timeouts on this version. Let me know if we'll need to bump any timeout values.

**Comment by hermanventer** [comment]
I find the timeouts to be non deterministic on my setup. Perhaps not too surprising. The time-out setting for the CI is a bit more generous. I'm OK with leaving things as is as long as CI does not get to be flaky.

**Pull request merged**
