### PR TITLE
Follow up to comments in 2357

### PR DESCRIPTION
**Pull request by trueadm**
Release notes: none

This is a follow up PR that addresses the post-land comments made in the PR #2357 from @sebmarkbage.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Now you can remove the flag in $OwnPropertyKeys, right? https://github.com/facebook/prepack/blob/master/src/values/ObjectValue.js#L725

**Comment by trueadm** [comment]
@sebmarkbage Nope, I tried that, we reference it via `AbstractObjectValue.$OwnPropertyKeys` and changing all those call-sites can be done at another time (I also thought they were only done via ObjectValue only).

**Comment by sebmarkbage** [comment]
I don't understand. You just added that flag in the previous diff and now you're removing the use case that it was added for.

AbstractObjectValue only passes it through to ObjectValue.

**Comment by trueadm** [comment]
@sebmarkbage It's this that's causing the issues https://github.com/facebook/prepack/pull/2381/commits/30a0493fc587115669718047cdde44219397cdfc#diff-5cb5f0c9909e8738d567acfaff9bb980R142. It passes the flag to AbstractObjectValue, that passes to ObjectValue. Unless I'm misunderstanding you.

**Pull request closed without merging**
