### PR TITLE
Support React keys in array branches, fixes #2139

### LINKED ISSUE #2139: Bug in React key branching when component returns an array
Failing test:

```js
var React = require('react');
this['React'] = React;

function Foo(props) {
  return [<div ref={props.callback} key="0" />];
}

function Bar(props) {
  return [<div ref={props.callback} key="0" />];
}

function App(props) {
  return props.foo ? <Foo {...props} /> : <Bar {...props} />;
}

if (this.__optimizeReactComponentTree) {
  __optimizeReactComponentTree(App);
}

App.getTrials = function(renderer, Root) {
  let counter = 0;
  let nodes = [];
  function callback(node) {
    nodes.push(node);
    counter++;
  }
  renderer.update(<Root callback={callback} foo={true} />);
  renderer.update(<Root callback={callback} foo={true} />);
  renderer.update(<Root callback={callback} foo={false} />);
  renderer.update(<Root callback={callback} foo={false} />);
  renderer.update(<Root callback={callback} foo={true} />);
  renderer.update(<Root callback={callback} foo={true} />);
  let results = [];
  results.push(['ensure ref is called on every change', counter]);
  results.push(['ensure refs are cleared', nodes.map(Boolean)]);
  results.push(['ensure refs are different', new Set(nodes).size]);
  return results;
};

module.exports = App;
```

In the output, the nodes are incorrectly reused.

### PR DESCRIPTION
**Pull request by trueadm**
Release notes: none

Add logic to support adding keys when inlining arrays. Fixes https://github.com/facebook/prepack/issues/2139.

### CODE REVIEW

**Comment by gaearon** [comment]
Can you also add tests for nesting arrays?

**Comment by trueadm** [comment]
@gaearon I've added some more tests with nested arrays.

**Comment by trueadm** [comment]
@gaearon Just saw this, I must have missed your reply. I've merged master and fixed the issue in question. I added support conditionals, it was missing the logic for them so it wouldn't add keys if a conditional existing in the returned branch. I'm not sure we need to go back to the drawing board on this, as I feel the logic holds but it might seem that it's hacky from your perspective. I'll happily talk you through it if that might help. I'll add some comments to the code now.

**Comment by gaearon** [comment]
These are helpful. Let’s review tomorrow in person?

**Pull request closed without merging**
