### PR TITLE
Use an existing property name to test throwing in global getters

### PR DESCRIPTION
**Pull request by sebmarkbage**
This works around in a bug in Node.js 7.x.x where added properties need to be copied over onto the original "sandbox" created by the VM module in the test-runner. That is done in native code which is not resilient to this getter throwing which causes a crash.

By using an existing property name, that path is skipped.

Are these tests intentionally duplicated?

### CODE REVIEW

**Comment by hermanventer** [comment]
I don't know the provenance of these tests, but I doubt that they are intentionally duplicated. I expect that there was an intention to create a wrapped property getter test along the lines of the unwrapped one.

**Comment by sebmarkbage** [comment]
What is a "wrapped property getter"? Maybe I can fix it.

**Comment by hermanventer** [comment]
I have no idea either. For now just delete the redundant test.

**Comment by NTillmann** [comment]
This should address #539.

**Pull request merged**
