### PR TITLE
test-runner now supports promises

### PR DESCRIPTION
**Pull request by prometheansacrifice**
Release note: none

Attempts adding support for promises in test-runner.js. `inspect` can now return Promises, which will be resolved before checking it value.

### CODE REVIEW

**Comment by trueadm** [comment]
Can you add a test has an `inspect` function with a Promise returning from it? Also, does the test runner wait until each async test has resolved before continuing to the next test?

**Comment by prometheansacrifice** [comment]
> Can you add a test has an inspect function with a Promise returning from it?

I can but it wouldn't serialize properly.

>  Also, does the test runner wait until each async test has resolved before continuing to the next test?

Yes, the next test is run only after the current test's promise is resolved.

**Comment by trueadm** [comment]
@prometheansacrifice Why would this work?

```js
function fn(resolve) {
  setTimeout(function() {
    resolve();
  }, 100);
}

inspect = function() {
  return new Promise(fn);
}
```

**Comment by prometheansacrifice** [comment]
@trueadm 

Serialized output for the snippet you posted

```js
var fn;
(function () {
  var _$0 = this;

  var _0 = function (resolve) {
    setTimeout(function () {
      resolve(6);
    }, 100);
  };

  var _1 = function () {
    return new Promise(fn);
  };

  _$0.fn = _0;
  _$0.inspect = _1;
}).call(this);
```

On the other hand, the following fails due to incomplete implementation of Promises

```js
var promise = Promise.resolve(3).then(val => val + 2);

inspect = function() {
  return promise;
}
```

**Pull request closed without merging**
