### PR TITLE
Support implicit abstract conversion during binary operations

### PR DESCRIPTION
**Pull request by prometheansacrifice**
Addresses #1109

### CODE REVIEW

**Comment by prometheansacrifice** [comment]
This patch works. Is this good enough? Should I create and use a `ToNumberOrAbstract` instead?

**Comment by hermanventer** [comment]
That sounds like a good idea because it avoids doing ToNumber yet again.

**Comment by prometheansacrifice** [comment]
But how can there be side effect? Evaluating a binary expression at [`computeBinary`](https://github.com/facebook/prepack/blob/master/src/evaluators/BinaryExpression.js#L166-L167) makes sure that operand are pure (not writing/reading to heap or throwing). What am I missing?

**Comment by prometheansacrifice** [comment]
Heres what I thought you meant:

ImplicitAbstractConversionWithSideEffects.js
```
let glob = 1;
let x = global.__abstract ? __abstract("number", "(3)") : 3;
let ob =  { valueOf: () => {
  glob += 1;
  return x;
}};
let ob2 =  { valueOf: () => {
  glob += 1;
  return 4;
}};

let y = 123 * ob * ob2;

inspect = function() { return y + ' ' + glob; }
```

**Comment by prometheansacrifice** [comment]
I'm a little confused. There's no binary expression in the above test that directly involves an AbstractValue.

**Comment by hermanventer** [comment]
Thinking about this some more I now realize that side-effects will not be an issue. Once a value is primitive, converting it to a number will never have a side effect. It is still a nice idea to avoid the second conversion, but it is not a correctness issue after all. Sorry about my fuzzy thinking on this.

**Comment by prometheansacrifice** [comment]
No problem. I'll update the PR soon.

**Pull request closed without merging**
