### PR TITLE
I  add demo record functionality to the website

### PR DESCRIPTION
**Pull request by sheweichun**
For more sufficient learning, I  add demo record functionality to the website,so I can record some demo for future learning

### CODE REVIEW

**Comment by 7tomir7** [comment]
Спасибо но уменя проблема с владением иностранных языков.🛡✌🛡



Отправлено со смартфона Samsung Galaxy.


-------- Исходное сообщение --------
От: Facebook Community Bot <notifications@github.com>
Дата: 07.05.2017 16:09 (GMT+03:00)
Кому: facebook/prepack <prepack@noreply.github.com>
Копия: Subscribed <subscribed@noreply.github.com>
Тема: Re: [facebook/prepack] I add demo record functionality to the website (#592)


Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by NTillmann** [comment]
That looks interesting, but something seems to have gone wrong with the git additions. Your pull request includes the test/test262 contents which is meant to be a submodule. Can you try to clean that up? Thanks!

**Comment by jbarber11** [comment]
Merge

**Comment by sheweichun** [comment]
I removed test/test262 and had merged with prepack/gh-pages branch

**Comment by sheweichun** [comment]
I recommit again,but it show `no test commands were found`,in fact, there isn't package.json

**Pull request merged**
